name: Asteroid Pipeline

on:
  schedule:
    - cron: "0 */6 * * *"   # tiap 6 jam
  workflow_dispatch:        # bisa run manual

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python -m app.pipeline
